### PR TITLE
fix overflow for maxMessageSize

### LINKED ISSUE #91: received message larger than max size of -1
Without setting the `amqp.LinkMaxMessageSize(...)` on a receiver, the max message size is -1, which causes an error. After setting `amqp.LinkMaxMessageSize(...)` I'm again able to receive messages.

### PR DESCRIPTION
**Pull request by devigned**
fixes #91 

- default maxMessageSize to 0 (infinite)
- set maxMessageSize if link.maxMessageSize is less than MaxInt32

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -1436,11 +1436,15 @@ func (r *Receiver) Receive(ctx context.Context) (*Message, error) {
...
-		maxMessageSize = int(r.link.maxMessageSize)
+		maxMessageSize = 0
 		messageSize    = 0
 		first          = true // receiving the first frame of the message
 	)
 
+	if r.link.maxMessageSize < math.MaxInt32 {
+		// if the max size is less than max int set, otherwise, it might as well be infinite
+		maxMessageSize = int(r.link.maxMessageSize)
+	}
```
Comment (vcabbage) [inline client.go]: I think it might be better to track the message size as an `uint64` instead of considering anything greater than `math.MaxInt32` unlimited. I think it's unlikely anyone transfers messages that large over AMQP but I don't want to completely disregard an explicitly configured max size.

Comment (devigned) [reply client.go]: rebased with uint64 support
