### PR TITLE
Fix Incorrect time calculation for dates before the Unix epoch

### LINKED ISSUE #173: Incorrect time calculation for dates before the Unix epoch
There is a signed/unsigned bug in readTimestamp() giving incorrect results for dates before the Unix epoch (before 1970) Pull request with regression test coming shortly.

### PR DESCRIPTION
**Pull request by alanconway**
AMQP timestamp is a signed value, but decoded from buffer as unsigned.
The previous code took the remainder of the unsigned value before
converting to signed which is incorrect for negative timestamps.

Fixes  #173

### CODE REVIEW

File: decode.go [hunk 1]
```diff
@@ -945,9 +945,8 @@ func readTimestamp(r *buffer) (time.Time, error) {
 		return time.Time{}, errorErrorf("invalid type for timestamp %02x", type_)
 	}
 
-	n, err := r.readUint64()
-	rem := n % 1000
```
Comment (vcabbage) [inline decode.go]: What do you think about converting to signed here and retaining the remainder logic to avoid overflow of the `int64` nanoseconds. It's a corner case since overflow would occur sometime in year 2262, but I think we should handle it.

Comment (alanconway) [reply decode.go]: Agreed and pushed. I was under the mistaken impression that time.Time was just int64 nanoseconds internally, but I looked it up and it's got  a bigger range so best not to lose any accuracy.

**Comment by vcabbage** [comment]
Thanks!
